apiVersion: backup.appuio.ch/v1alpha1
kind: Restore
metadata:
  name: restore-database
spec:
  keepJobs: 1
  restoreMethod:
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: restore
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: password
  backend:
    repoPasswordSecretRef:
      name: k8up-backup-repo
      key: password
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: backup
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: password
