groups:
- name: backup failed
  rules:
  - alert: K8upBackupFailed
    expr: rate(k8up_jobs_failed_count[1d]) > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Job in {{ $labels.namespace }} of type {{ $labels.jobType }} failed"
- name: no jobs finished within 24 hours
  rules:
  - alert: K8upBackupNotRunning
    expr: rate(k8up_jobs_total[1d]) == 0 and on(namespace) k8up_schedules_gauge > 0
    for: 25h
    labels:
      severity: critical
    annotations:
      summary: "No K8up jobs were run in {{ $labels.namespace }} within the last 24 hours. Check the operator, there might be a deadlock"
