# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
# The `latest` is not touched for pre release.
# The template string `{{ if .Prerelease }}v{{ .Version }}{{ else }}latest{{ end }}`
# will compute to `latest` for regular release. For pre releases, it will
# compute to `v{{ .Version }}`. This duplicates one of the other list items
# and therefore eliminates `latest` from the list. This is OK to do since
# `goreleaser` builds the image only once and tagging is a cheap operation.
- image_templates:
  - "docker.io/vshn/k8up:{{ if .Prerelease }}v{{ .Version }}{{ else }}latest{{ end }}"
  - "docker.io/vshn/k8up:v{{ .Version }}"
  - "docker.io/vshn/k8up:v{{ .Major }}"
  - "quay.io/vshn/k8up:{{ if .Prerelease }}v{{ .Version }}{{ else }}latest{{ end }}"
  - "quay.io/vshn/k8up:v{{ .Version }}"
  - "quay.io/vshn/k8up:v{{ .Major }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^(D|d)oc(s|umentation):'
    - '^(T|t)ests?:'
    - '^(R|r)efactor:'
    - '^Merge pull request'

release:
  prerelease: auto

  github:
    owner: vshn
    name: k8up
  extra_files:
  - glob: ./k8up-crd*.yaml
