site_name: K8up

theme: readthedocs

nav:
  - Home: index.md
  - "Getting Started": getting-started.md
  - "Advanced Configuration": advanced-config.md
  - Restore: restore.md
  - "Object Specifications": object-specifications.md

markdown_extensions:
  - admonition
