site:
  title: K8up Documentation
  url: https://k8up.io/
  start_page: k8up::index.adoc
content:
  sources:
  - url: https://github.com/vshn/k8up.git
    branches: feature/asciidoc
# ui:
#   bundle:
#     url: ./ui/ui-bundle.zip
#     snapshot: true
output:
  destinations:
  - provider: fs
    path: ./public
    clean: true
  - provider: archive
    path: ./_archive/site.zip
    clean: true
