site:
  title: "DRAFT: K8up Documentation"
  url: http://localhost/
  start_page: docs::index.adoc
content:
  sources:
  - url: .                 # The current folder is a git repo
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: docs
ui:
  bundle:
    url: https://github.com/vshn/antora-ui-default/releases/download/1.7/ui-bundle.zip
    snapshot: false
asciidoc:
  attributes:
    toc: 'auto'
    toc-title: ''
    toclevels: 2
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://vshn-kroki.appuioapp.ch
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_public
    clean: true
  - provider: archive
    path: ./_archive/site.zip
    clean: true
