apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: k8up
        image: quay.io/vshn/k8up:latest
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
