---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: k8up
        image: $E2E_IMAGE
        args:
          - operator
        env:
        - name: BACKUP_LOG_LEVEL
          value: debug
        - name: BACKUP_IMAGE
          value: $E2E_IMAGE
        - name: BACKUP_ENABLE_LEADER_ELECTION
          value: $BACKUP_ENABLE_LEADER_ELECTION
