---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject
  template:
    metadata:
      labels:
        app: subject
    spec:
      containers:
      - name: subject-container
        image: quay.io/prometheus/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - |
          printf '$BACKUP_FILE_CONTENT' | tee '/data/$BACKUP_FILE_NAME' && \
          ls -la /data && \
          echo "test file '/data/$BACKUP_FILE_NAME' written, sleeping now" && \
          sleep infinity
        securityContext:
          runAsUser: $ID
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: subject-pvc
