---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject
  template:
    metadata:
      labels:
        app: subject
    spec:
      containers:
      - name: subject-container
        image: $BUSYBOX_IMAGE
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - |
          date +%s | tee /data/expectation.txt && \
          ls -la /data && \
          echo 'test file written, sleeping now' && \
          sleep infinity
        securityContext:
          runAsUser: $ID
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: subject-pvc
