apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-pv
  labels:
    pv.kubernetes.io/type: e2e-test
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /pv/data/pvc-subject
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
