# permissions for end users to view archives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: archive-viewer-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - archives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - archives/status
  verbs:
  - get
