# permissions for end users to view backups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - backups/status
  verbs:
  - get
