# permissions for end users to view checks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: check-viewer-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - checks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - checks/status
  verbs:
  - get
