# permissions for end users to edit checks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: check-editor-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - checks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - checks/status
  verbs:
  - get
