# permissions for end users to view prebackuppods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prebackuppods-viewer-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - prebackuppods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - prebackuppods/status
  verbs:
  - get
