# permissions for end users to view prebackuppods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prebackuppod-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - prebackuppods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - prebackuppods/status
  verbs:
  - get
