# permissions for end users to edit prebackuppods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prebackuppods-editor-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - prebackuppods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - prebackuppods/status
  verbs:
  - get
