# permissions for end users to edit prunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prune-editor-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - prunes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - prunes/status
  verbs:
  - get
