# permissions for end users to view prunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prune-viewer-role
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - prunes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - prunes/status
  verbs:
  - get
