# permissions for end users to view prunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prune-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - k8up.syn.tools
  resources:
  - prunes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8up.syn.tools
  resources:
  - prunes/status
  verbs:
  - get
