apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
data:
  username: OFUwVUROWVBOVURUVVMxTElBRjM=
  password: aXAzY2Rya1hjSG1INFM3aWY3ZXJLUE5veERuMjdWMHZyZzZDSEhlbQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-repo
type: Opaque
data:
  password: YXNkZg==
