apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
stringData:
  username: 8U0UDNYPNUDTUS1LIAF3
  password: ip3cdrkXcHmH4S7if7erKPNoxDn27V0vrg6CHHem
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-repo
type: Opaque
stringData:
  password: asdf
