---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: baas-operator
subjects:
- kind: ServiceAccount
  namespace: appuio-baas-operator
  name: baas-operator
  apiGroup:
roleRef:
  kind: ClusterRole
  name: baas-operator
  apiGroup: rbac.authorization.k8s.io
