---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: crd-creator-global
subjects:
- kind: ServiceAccount
  namespace: myproject
  name: backup-account
  apiGroup:
roleRef:
  kind: ClusterRole
  name: crd-creator
  apiGroup: rbac.authorization.k8s.io
