---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: baas
  labels:
    app: baas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baas
  template:
    metadata:
      labels:
        app: baas
    spec:
      containers:
        - name: baas-operator
          image: 172.30.1.1:5000/myproject/baas:0.0.1
          imagePullPolicy: Always
          env:
            - name: BACKUP_IMAGE
              value: 172.30.1.1:5000/myproject/test:latest
            - name: BACKUP_GLOBALACCESSKEYID
              value: 8U0UDNYPNUDTUS1LIAF3
            - name: BACKUP_GLOBALSECRETACCESSKEY
              value: ip3cdrkXcHmH4S7if7erKPNoxDn27V0vrg6CHHem
            - name: BACKUP_GLOBALREPOPASSWORD
              value: password
      serviceAccountName: baas-operator

#kubectl create clusterrolebinding cluster-admin-binding-2   --clusterrole=cluster-admin   --user=system:system:serviceaccount:myproject:default
