---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-executor
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/exec
  verbs:
  - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-executor-namespaced
subjects:
- kind: ServiceAccount
  name: pod-executor
  apiGroup:
roleRef:
  kind: ClusterRole
  name: pod-executor
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-executor


