apiVersion: v1
groupNames:
- system:authenticated
kind: RoleBinding
metadata:
  name: shared-resource-viewers
roleRef:
  name: shared-resource-viewer
  namespace: appuio-baas-operator
subjects:
- kind: SystemGroup
  name: system:authenticated
userNames: null
