---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotated-subject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject
  template:
    metadata:
      labels:
        app: subject
      annotations:
        k8up.io/backupcommand: '/tmp/test.sh'
        k8up.io/file-extension: '.txt'
    spec:
      containers:
      - name: subject-container
        image: quay.io/prometheus/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - |
          printf '$BACKUP_FILE_CONTENT' | tee '/data/$BACKUP_FILE_NAME' && \
          printf '#!/bin/sh\nsleep 30s\necho $BACKUP_FILE_CONTENT\n' | tee /tmp/test.sh && chmod a+x /tmp/test.sh && \
          echo && \
          ls -la /data && \
          echo "test file '/data/$BACKUP_FILE_NAME' written, sleeping now" && \
          sleep infinity
        securityContext:
          runAsUser: $ID
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: subject-pvc
