kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    k8up.io/backup: 'true'
  namespace: myproject
spec:
  accessModes:
    - ReadWriteMany
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  # storageClassName: slow
