---
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: resources-schedule
spec:
  keepJobs: 1
  resourceRequirementsTemplate:
    limits:
      cpu: "500m"
    requests:
      cpu: "20m"
      memory: "30Mi"
  backend:
    repoPasswordSecretRef:
      name: k8up-backup-repo
      key: password
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: backup
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: password

  backup:
    schedule: '* * * * *'
    resources:
      requests:
        cpu: "250m"
