apiVersion: appuio.ch/v1alpha1
kind: Backup
metadata:
  name: baas-test
  namespace: myproject
spec:
  dryRun: true
  schedule: "* * * * *" #every minute
  # checkSchedule: "* * * * *"
  keepJobs: 4
  backend:
    s3:
      endpoint: http://10.144.1.133:9000
      bucket: baas
  retention:
    keepLast: 2
    keepDaily: 14
  promURL: http://10.144.1.133:9091
