kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    appuio.ch/backup: true
  namespace: myproject
spec:
  accessModes:
    - ReadWriteMany
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  # storageClassName: slow
