# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- base/k8up.io_schedules.yaml
- base/k8up.io_backups.yaml
- base/k8up.io_restores.yaml
- base/k8up.io_archives.yaml
- base/k8up.io_checks.yaml
- base/k8up.io_prunes.yaml
- base/k8up.io_snapshots.yaml
- base/k8up.io_prebackuppods.yaml
- base/k8up.io_effectiveschedules.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
