---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: k8up
        image: $E2E_IMAGE
        env:
        - name: BACKUP_LOG_LEVEL
          value: debug
