resources:
- ../../../config/manager
- ../../../config/rbac
- ../../../config/namespace
patchesStrategicMerge:
- deployment.yaml
namespace: k8up-system
namePrefix: k8up-

commonLabels:
  app.kubernetes.io/name: e2e
  app.kubernetes.io/managed-by: kustomize
