apiVersion: backup.appuio.ch/v1alpha1
kind: Backup
metadata:
  name: backup-database
spec:
  backend:
    repoPasswordSecretRef:
      name: k8up-backup-repo
      key: password
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: backup
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: password
