apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: k8up-restore
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  restoreMethod:
    folder:
      claimName: subject-pvc
  backend:
    repoPasswordSecretRef:
      name: k8up-backup-repo
      key: password
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: backup
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: password
  podSecurityContext:
    runAsUser: $ID
